# Generated by Django 3.2.16 on 2023-01-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationid',
            name='value',
            field=models.CharField(max_length=36),
        ),
    ]
