# Generated by Django 3.2.16 on 2023-01-27 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_mfamodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mfamodel',
            name='last_used',
        ),
    ]
